spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/testDB
    username: postgres
    password: test

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true


  thymeleaf:
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

  profiles:
    include: window